CREATE TABLE entries
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    in_ukrainian VARCHAR(255),
    in_russian   VARCHAR(255),
    in_english   VARCHAR(255)
);

CREATE INDEX in_ukrainian_index ON entries (in_ukrainian);
